---
- hosts: localhost
  tasks:
  - name: Create a directory for each client
    file:
      path: "/etc/wireguard/clients/{{ clientName }}"
      state: directory
      owner: root
      group: root
      mode: 0600


  - name: Generate private and public key for each client
    shell: "umask 077; wg genkey | tee client.key | wg pubkey > client.pub"
    args:
      chdir: "/etc/wireguard/clients/{{ clientName }}"
      creates: client.key
   

  - name: Register client public keys
    command: cat client.pub
    args:
      chdir: "/etc/wireguard/clients/{{ clientName }}"
   
    register: wireguard_client_pubkeys
    changed_when: False

  - name: Register client private keys
    command: cat client.key
    args:
      chdir: "/etc/wireguard/clients/{{ clientName }}"
    
    register: wireguard_client_privkeys
    changed_when: False

  - name: Generate the client configuration profiles
    template:
      src: client.conf.j2
      dest: "/etc/wireguard/clients/{{ clientName }}/client.conf"
  

  - name: Generate OpenWrt configuration fragments
    template:
      src: client-openwrt.txt.j2
      dest: "/etc/wireguard/clients/{{ clientName }}/client-openwrt.txt"
    
  - service:
      name: dnsmasq
      state: restarted

# - import_tasks: docs.yml
